cnn:
  augmentation_multiplier: 0.2
  layers:
  - depth: 16
    group_norm_num_groups: 16
    kernel_size:
    - 3
    - 3
  - depth: 16
    group_norm_num_groups: 16
    kernel_size:
    - 3
    - 3
  - depth: 32
    group_norm_num_groups: 32
    kernel_size:
    - 3
    - 3
  - depth: 32
    group_norm_num_groups: 32
    kernel_size:
    - 3
    - 3
  - depth: 64
    group_norm_num_groups: 32
    kernel_size:
    - 3
    - 3
  - depth: 64
    group_norm_num_groups: 32
    kernel_size:
    - 3
    - 3
  - depth: 128
    group_norm_num_groups: 32
    kernel_size:
    - 3
    - 3
  - depth: 128
    group_norm_num_groups: 32
    kernel_size:
    - 3
    - 3
  - depth: 256
    group_norm_num_groups: 32
    kernel_size:
    - 3
    - 3
  - depth: 256
    group_norm_num_groups: 32
    kernel_size:
    - 3
    - 3
  pool_size: 2
  resblock_size: 3
display:
  refresh_rate: 10
learning:
  batch_size: 100
  dropout_prob: 0.2
  learning_patience: 4000
  learning_rates:
  - 0.001
  - 0.0005
  - 0.0001
  - 0.00005
  - 0.000001
  num_iters: 1000000
  weight_decay: 0.005
mlp:
  hidden_layer_width: 200
  num_hidden_layers: 1
