data:
  context_length: 4
display:
  refresh_rate: 5
learning:
  batch_size: 500
  learning_patience: 20
  learning_rates:
  - 0.0005
  - 0.0001
  - 5.0e-05
  - 1.0e-05
  num_iters: 100000
  weight_decay: 0.2
transformer:
  ffn_dim: 2048
  model_dim: 512
  num_blocks: 6
  num_heads: 8
