display:
  refresh_rate: 5
learning:
  val_check_rate: 10
  batch_size: 500
  dropout_prob: 0.2
  learning_patience: 20 
  learning_rates:
  - 0.0005
  - 0.0001
  - 0.0005
  - 0.00001
  num_iters: 100000
  weight_decay: 0.2
  num_embeddings: 10000
  embedding_depth: 10000 
mlp:
  hidden_layer_width: 500
  num_hidden_layers: 1
data:
  num_words_to_tokenize: 50
