cnn:
  layer_depths: [30, 30, 30, 30, 30]
  kernel_sizes: [[5,5], [4,4], [3,3], [3,3], [3,3]]
  pool_every_n_layers: 3
  pool_size: 2
  resblock_size: 2
mlp:
  num_hidden_layers: 2
  hidden_layer_width: 1024
learning:
  weight_decay: 0.002
  dropout_first_n_fc_layers: 2
  dropout_prob: 0.25
  batch_size: 2000
  num_iters: 5000
  learning_rates: [.0005, .00045, .0004, .0003, .00001, .000008]
  learning_patience: 100 
display:
  refresh_rate: 5