cnn:
  layer_depths: [40, 40, 40, 40]
  kernel_sizes: [[2,2], [2, 2], [2, 2], [2, 2]]
  pool_every_n_layers: 2
  pool_size: 2
  resblock_size: 2
mlp:
  num_hidden_layers: 4
  hidden_layer_width: 1000
learning:
  weight_decay: 0.05
  dropout_first_n_fc_layers: 2
  dropout_prob: 0.5
  batch_size: 2000
  num_iters: 5000
  learning_rates: [.0005, .00045, .0004, .0003, .00001, .000008]
  learning_patience: 30 
display:
  refresh_rate: 5