cnn:
  layer_depths: [32, 32, 32, 32]
  kernel_sizes: [[3,3], [3,3], [3,3], [3,3]]
  pool_every_n_layers: 2
  pool_size: 2
mlp:
  num_hidden_layers: 4
  hidden_layer_width: 500
learning:
  weight_decay: 0.0005
  dropout_first_n_fc_layers: 2
  dropout_prob: 0.5
  batch_size: 2000
  num_iters: 500
  learning_rates: [.0001, .00001, .000001]
  learning_patience: 100
display:
  refresh_rate: 5