cnn:
  layers:
    - depth: 64
      kernel_size: [3, 3]
      group_norm_num_groups: 8
    - depth: 128
      kernel_size: [3, 3]
      group_norm_num_groups: 16
    - depth: 256
      kernel_size: [3, 3]
      group_norm_num_groups: 32
    # - depth: 512
    #   kernel_size: [3, 3]
    #   group_norm_num_groups: 64
  pool_size: 2
  resblock_size: 2
  num_classes: 10
  augmentation_prob: 0.2
  num_augmentation_attempts: 3
learning:
  weight_decay: 0.5
  dropout_prob: 0
  batch_size: 500
  num_iters: 100000
  learning_rates: [.001, .005, .01, .005, .001, .0005, .0002, .0001, .0001]
  learning_patience: 5
display:
  refresh_rate: 5