display:
  refresh_rate: 5
learning:
  batch_size: 1
  learning_patience: 15 
  learning_rates:
  - 0.0005
  - 0.0001
  - 0.00005
  - 0.00001
  num_iters: 2000 
  weight_decay: 0.2
siren:
  num_hidden_layers: 10
  hidden_layer_width: 256
  resolution: 256
