cnn:
  augmentation_multiplier: 0.2
  layers:
  - depth: 8
    group_norm_num_groups: 8
    kernel_size:
    - 3
    - 3
  - depth: 16
    group_norm_num_groups: 16
    kernel_size:
    - 3
    - 3
  - depth: 32
    group_norm_num_groups: 32
    kernel_size:
    - 3
    - 3
  - depth: 64
    group_norm_num_groups: 32
    kernel_size:
    - 3
    - 3
  - depth: 128
    group_norm_num_groups: 32
    kernel_size:
    - 3
    - 3
  pool_size: 2
  resblock_size: 2
display:
  refresh_rate: 5
learning:
  batch_size: 1000
  dropout_prob: 0.2
  learning_patience: 200
  learning_rates:
  - 0.0005
  - 0.0001
  - 0.0005
  - 0.001
  - 0.0005
  - 0.0001
  - 0.00005
  - 0.00001
  num_iters: 100000
  weight_decay: 0.05
mlp:
  hidden_layer_width: 1000
  num_hidden_layers: 2
