cnn:
  layer_depths: [50, 50]
  kernel_sizes: [[2,2], [2,2]]
  pool_every_n_layers: 2
  pool_size: 2
  resblock_size: 2
  num_classes: 10
  num_augmentations: 2
mlp:
  num_hidden_layers: 4
  hidden_layer_width: 1024
learning:
  weight_decay: 0.2
  dropout_first_n_fc_layers: 2
  dropout_prob: 0.5
  batch_size: 2000
  num_iters: 5000
  learning_rates: [.001, .0005, .0002, .0001, .00005]
  learning_patience: 200 
display:
  refresh_rate: 5