mlp:
  num_hidden_layers: 4
  hidden_layer_width: 128
basis_expansion:
  num_bases: 7 
learning:
  step_size: .5
  batch_size: 128
  num_iters: 4000
  decay_rate: 0.999
data:
  num_samples: 500
  noise_stddev: .4
display:
  refresh_rate: 10