cnn:
  layer_depths: [10, 10]
  kernel_sizes: [[2,2], [5,5]]
  pool_every_n_layers: 2
  pool_size: 2
mlp:
  num_hidden_layers: 4
  hidden_layer_width: 400
basis_expansion:
  num_bases: 7 
learning:
  weight_decay: 0.005
  dropout_prob: .4
  batch_size: 1500
  num_iters: 2000 
  learning_rate: 0.0005
display:
  refresh_rate: 10