cnn:
  layer_depths: [10, 10]
  kernel_sizes: [[2,2], [2,2]]
  pool_every_n_layers: 0
  pool_size: 2
mlp:
  num_hidden_layers: 3
  hidden_layer_width: 500
learning:
  weight_decay: 0.05
  dropout_prob: 0.5
  batch_size: 2000
  num_iters: 5000
  learning_rate: .00001
  learning_patience: 100
display:
  refresh_rate: 5