cnn:
  layer_depths: [30, 30, 30]
  kernel_sizes: [[5,5], [4,4], [3,3]]
  pool_every_n_layers: 2
  pool_size: 2
mlp:
  num_hidden_layers: 4
  hidden_layer_width: 10
basis_expansion:
  num_bases: 7 
learning:
  l2_scale: .001
  dropout_prob: 0.1
  batch_size: 5
  num_iters: 20000 
  learning_rate: 0.000001
display:
  refresh_rate: 10