cnn:
  layer_depths: [10, 10]
  kernel_sizes: [[2,2], [5,5]]
  pool_every_n_layers: 2
  pool_size: 2
mlp:
  num_hidden_layers: 4
  hidden_layer_width: 200
basis_expansion:
  num_bases: 7 
learning:
  l2_scale: 0.001
  dropout_prob: .3
  batch_size: 500
  num_iters: 20 
  learning_rate: 0.001
display:
  refresh_rate: 5