cnn:
  layer_depths: [4, 8]
  kernel_sizes: [[5,5], [3,3]]
  pool_every_n_layers: 2
  pool_size: 2
mlp:
  num_hidden_layers: 4
  hidden_layer_width: 20
basis_expansion:
  num_bases: 7 
learning:
  l2_scale: .01
  dropout_prob: 0.2
  batch_size: 1000
  num_iters: 20000 
  learning_rate: 0.001
display:
  refresh_rate: 10