cnn:
  layer_depths: [5, 5]
  kernel_sizes: [[5,5], [5,5]]
  pool_every_n_layers: 2
  pool_size: 2
mlp:
  num_hidden_layers: 3
  hidden_layer_width: 300
basis_expansion:
  num_bases: 7 
learning:
  l2_scale: 1
  dropout_prob: 0.5
  batch_size: 1000
  num_iters: 10000 
  learning_rate: 0.0001
display:
  refresh_rate: 10