cnn:
  layer_depths: [10, 10]
  kernel_sizes: [[4,4], [2,2]]
  pool_every_n_layers: 2
  pool_size: 2
mlp:
  num_hidden_layers: 2
  hidden_layer_width: 300
basis_expansion:
  num_bases: 7 
learning:
  l2_scale: 0.1
  dropout_prob: .5
  batch_size: 1000
  num_iters: 5000 
  learning_rate: 0.001
display:
  refresh_rate: 10