cnn:
  layer_depths: [10, 10, 10, 10]
  kernel_sizes: [[2,2], [2,2], [2,2], [2,2]]
  pool_every_n_layers: 4
  pool_size: 2
mlp:
  num_hidden_layers: 2
  hidden_layer_width: 200
basis_expansion:
  num_bases: 7 
learning:
  weight_decay: 0.005
  dropout_prob: 0.001 
  batch_size: 2000
  num_iters: 2000
  learning_rate: 0.0001
  learning_patience: 50
display:
  refresh_rate: 10