display:
  refresh_rate: 5
learning:
  val_check_rate: 10
  batch_size: 100
  learning_patience: 20 
  learning_rates:
  - 0.0005
  - 0.0001
  - 0.0005
  - 0.00001
  num_iters: 100000
  weight_decay: 0.2
  num_embeddings: 5000
  embedding_depth: 5000 
data:
  num_words_to_tokenize: 3
transformer:
  num_heads: 8
  model_dim: 512
  ffn_dim: 2048
  num_blocks: 6
