display:
  refresh_rate: 5
learning:
  batch_size: 5
  learning_patience: 20 
  learning_rates:
  - 0.0005
  - 0.0001
  - 0.0005
  - 0.00001
  num_iters: 100000
  weight_decay: 0.2
data:
  context_length: 4 
  min_vocab_size: 100
transformer:
  num_heads: 8
  model_dim: 512
  ffn_dim: 2048
  num_blocks: 6
